### ISSUE TITLE
Release next alpha version

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#562]
Release the  next alpha version with changes so far.

```[tasklist]
### Tasks
- [x] Bump version
- [x] Clear cache of earthquakes layer (fetch + wip)
- [x] Clear cache for bedmachine layers (fetch + wip)
- [x] Clear cache for WOA layers
- [x] clear cache for sea ice layers(?)
- [x] clear cache for mineral and hydrocarbon licenses layers
- [x] clear cache for esa cci elevation change layers & replace dataset in private cache
```

**Comment by trey-stafford** [comment]
Probably don't need to clear the sea ice layer cache because we're just adding new assets and layers, not updating existing layers.

**Comment by trey-stafford** [comment]
In prod, fetched datasets are at: `/qgreenland-tmp/working-storage/fetch-datasets/`
