### ISSUE TITLE
Add layer quality checklist(s) in the contributor documentation

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#615]
We want our quality checklist saved somewhere, but we feel it's not necessary to attach it to each ticket. The checklist we were using in Jira last year:

```
- [ ] (R) Interpolation algorithm OK? (almost everything is currently bilinear, see notes for exceptions)
- [ ] (R) Grid resolution in layer title or group (incl. units)?
- [ ] (V) Polygon labels inside polygons
- [ ] (V) All attributes have reasonable types
- [ ] (R) Target resolution specified (see notes for exceptions)
- [ ] Abstract populated
- [ ] Citation populated
- [ ] Layer descriptions populated
- [ ] Layer description excludes data provider
- [ ] Layers'/groups' title follows date standard
- [ ] Layers'/groups' title follows capitalization standard
- [ ] Layers'/groups' title excludes data provider (see notes for exceptions)
- [ ] No fields are populated with "TBD" or "TODO"
- [ ] All layers have style
- [ ] Any known issues with data quality are listed in "Description"
- [ ] Datastore's data is in final state
- [ ] Layers not in unneccessary group
- [ ] PO approves citation
- [ ] PO approves description
```

Are there things in this checklist that can go in configuration validators?
