### ISSUE TITLE
Call for v3 feedback

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#679]
Reach out to:

- [x] Researcher workshop (Discussions + Slack) (dev)
- [x]  Cryolist (Alyse)
- [x] GitHub (README) (dev)
- [x] Editorial board (Twila)
- [x] Newsletter (Alyse)

Make a draft Google Form for this feedback process, as we can't rely on all our users having GitHub accounts.
```[tasklist]
### Tasks
- [x] Make a draft Google Form
- [x] Make a draft communication prose
```

**Comment by MattF-NSIDC** [comment]
We're excited to announce that QGreenland v3 is well underway! We have a pre-release (QGreenland `v3.0.0alpha4`) that we would like your feedback on.

You can find a full list of changes so far in v3 in our [CHANGELOG](https://github.com/nsidc/qgreenland/blob/main/CHANGELOG.md), but these are the highlights:

* Updated minimum supported QGIS version to 3.28 LTS.
* Resolved an error message related to missing "Helvetica" font in some operating systems.
* Many new layers, including:
    * New Asiaq/NunaGIS layers: `Places/Buildings`, `Places/Roads`
    * `Geology/Tectonic plates`
    * ``Internet-required data/Topographic map of Greenland`
    * `Internet-required data/Satellite orthophoto mosaic (10-0.2m)`
    * `Internet-required data/Blue Marble shaded relief and Bathymetry (500m)`
* Updated some datasets to their newest version, including:
    * BedMachine v5
    * Sea Ice Index 2022
    * Geothermal Heat Flow (Colgan et al.) v2
    * World Ocean Atlas 2023
    * Climate Change Initiative v3
* Removed some layers, including:
    * Humanitarian Open Street Maps
    * `Biology/Fish/Arctic Char`

**Comment by twilamoon-science** [comment]
Note that I changed the call-out style for the layers. I think Group>Layer makes more sense re: how navigation works than Group/Layer. Though I realize the latter is more relatable to the download file structure. 

Which layers are "climate change initiative v3"?

**Comment by MattF-NSIDC** [comment]
>Which layers are "climate change initiative v3"?

`Glaciology>Surface elevation change`!

**Comment by MattF-NSIDC** [comment]
Added a troubleshooting section.

**Comment by MattF-NSIDC** [comment]
@alysethurber all TODOs in the text are resolved.
